const ACTIONS={
    LOGIN:'LOGIN',
    GET_TOKEN:'GET_TOKEN',
    GET_USER:'GET_USER',
    LOGOUT:'LOGOUT',
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    STARTAPPT:'STARTAPPT',
    ENDAPPT:'ENDAPPT',
    CURRENTPATIENTID:'CURRENTPATIENTID',
    STATS:'STATS'
}
export default ACTIONS;
